#! /bin/sh
#
# Copyright (c) 2001-2002 SuSE Linux AG, Nuernberg, Germany.
# All rights reserved.
#
# /etc/init.d/ports
#
### BEGIN INIT INFO
# Provides:          wdt
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 5
# Default-Stop:
# Description:       Load PowerQuicc watchdog driver
### END INIT INFO

. /etc/rc.status

rc_reset

KILL_WDT=/opt/active/usr/bin/killwdt

if [ -r /etc/flashmount ]; then
    # defining the FLASH_PATH variable:
    . /etc/flashmount
fi

MODPROBE=${FLASH_PATH}/sbin/modprobe
device=wdt
module="wdt" 

case "$1" in
  start)
	    echo  -n "Loading ${device} driver "
		if [ ! -x $MODPROBE ] ; then
			echo -n "Error: $MODPROBE not found!"
			rc_failed 1
		else
			$MODPROBE ${device}
			if test $? -eq 0 ; then
				rm -f /dev/${device}   2>&1
				minor=`cat /proc/misc | grep ${module} | sed -e 's/^[^0-9]*//' | cut -d " " -f 1`
				#echo "${module}-driver uses misc-device minor-number ${minor}"
				mknod /dev/${device} c 10 ${minor}
				#give appropriate group/permissions,and change the group. 
				group="root"
				mode="664" 
				chgrp $group /dev/${device} 
				chmod $mode /dev/${device}
				
				# start the inital wdt process (PID1) here 
				# ${KILL_WDT} start

			else
				rc_failed 1
			fi
		fi
	    rc_status -v -r
	
	;;
    restart)
	    echo -n "Restart  ${device} driver "
		if [ ! -x $MODPROBE ] ; then
			echo -n "Error: $MODPROBE not found!"
			rc_failed 1
		else
		        rm -f /dev/${device}
		        $MODPROBE -r ${device}
			$MODPROBE ${device}
			if test $? -eq 0 ; then
				rm -f /dev/${device}   2>&1
				minor=`cat /proc/misc | grep ${module} | sed -e 's/^[^0-9]*//' | cut -d " " -f 1`
				echo "${module}-driver uses misc-device minor-number ${minor}"
				mknod /dev/${device} c 10 ${minor}
				#give appropriate group/permissions,and change the group. 
				group="root"
				mode="664" 
				chgrp $group /dev/${device} 
				chmod $mode /dev/${device}

			else
				rc_failed 1
			fi
		fi
	    rc_status -v -r
	;;
    stop)
	    echo -n "Unloading  ${device} driver "
		rm -f /dev/${device}
		$MODPROBE -r ${device}
		rc_status -v
	;;
    status)
	rc_failed 4
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac

rc_exit
	
