
obj-$(CONFIG_FSL_TLU) := fsl_tlu.o fsl_tlu_test.o fsl_tlu_rc.o

fsl_tlu-y :=	crt.o htk.o tlu_access.o tlu_heap.o  tlu_iptd.o  tlu_module.o \
		tlu.o tlu_bank.o tlu_export.o tlu_hw.o tlu_log.o

fsl_tlu_test-y := test_module.o test.o perf.o

fsl_tlu_rc-y   := route_cache_module.o  route_cache.o
