#!/bin/bash

export ARCH=powerpc

export PATH=/cross/opt/ppc4.1/usr/bin:$PATH

export CROSS_COMPILE=ppc_85xxDP-

make p1020rdb-pc.dtb
cp ./arch/powerpc/boot/p1020rdb-pc.dtb /home/dowslake/tftp/1604-dtb
cp ./arch/powerpc/boot/p1020rdb-pc.dtb /home/dowslake/mts180/ramfs/1604C/1604-dtb




