#!/bin/bash


export PATH=/cross/opt/ppc4.1/usr/bin:$PATH

export CROSS_COMPILE=ppc_85xxDP-

#cp ./.config ../configs/mts1080e_config_`date +%F_%H-%M-%S`

#make menuconfig ARCH=ppc
make menuconfig ARCH=powerpc

