#
# Makefile for the TDM bus drivers.
#

obj-$(CONFIG_TDM_FSL_STARLITE)	+= tdm_fsl_starlite.o
obj-$(CONFIG_FSL_UCC_TDM)	+= fsl_ucc_tdm.o
#ifeq ($(CONFIG_TDM_DEBUG_BUS),y)
#EXTRA_CFLAGS += -DDEBUG
#endif
